image: docker

services:
  - docker:dind




stages:
  - prepare
  - build
  - release
  - deploy
  - undeploy

variables:
  domain: merco.net
  project: lamp

Prepare:
  stage: prepare
  tags:
    - docker
  before_script:
    - echo Setting up $project.$domain
    - uptime
    - whoami
    - uname -a
  script:
    - ps aux
  only:
    - master

Build:
  stage: build
  tags:
    - docker
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker --version
    - docker-compose --version
  script:
    - docker-compose build
  only:
    - master

Release:
  stage: release 
  tags:
    - docker
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker --version
    - docker-compose --version
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker-compose push
  only:
    - master

Deploy:
  stage: deploy
  tags:
    - docker
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker --version
    - docker-compose --version
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker-compose up -d
  only:
    - master
  when: manual

Undeploy:
  stage: undeploy
  tags:
    - docker
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker --version
    - docker-compose --version
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker-compose down --volumes --remove-orphans
  only:
    - master
  when: manual

