version: "3.2"

services:

  php:

    image: registry.gitlab.com/merco.net/php:stable
    build: ./
    ports:
      - "80:80"
    links:
      - mysql
    volumes:
      - ./www/:/var/www/html/

  mysql:

    image: mysql:5.6.40
    environment:
      - MYSQL_ROOT_PASSWORD=YourMySQLPassword
      - MYSQL_DATABASE=php-database
      - MYSQL_USER=php-user
      - MYSQL_PASSWORD=YourDatabasePassword
